#!/usr/bin/env bash
## -*- mode: sh-mode; coding: utf-8 -*-

# Homebrew
if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    . "$(brew --prefix)/etc/bash_completion"
fi

# The Fuck
eval "$(thefuck --alias)"
