#!/usr/bin/env bash
## -*- mode: sh-mode; coding: utf-8 -*-

# Don't put duplicate lines or lines starting with space in the history.
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Language
LANG=ja_JP.UTF-8


#
# Paths
#

export PATH=/usr/local/bin:$PATH

# dotfiles
export PATH=$HOME/dotfiles/bin:$PATH

# bist
export PATH=$HOME/.bist/bin:$PATH

# anyenv
if [ -d $HOME/.anyenv ] ; then
  export PATH="$HOME/.anyenv/bin:$PATH"
  eval "$(anyenv init -)"
fi

#
# Homebrew
#

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

### cheat command
export CHEATCOLORS=true


#
# Emacs
#

export EMACS_HOME=$HOME/.emacs.d
export PATH=$EMACS_HOME/bin:$PATH
export EDITOR=emacsclient
#export VISUAL='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient'
export ALTERNATE_EDITOR='/Applications/Emacs.app/Contents/MacOS/Emacs'


#
# Java
#

# export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)  # Refer jenv(anyenv)
# export PATH=$JAVA_HOME/bin:$PATH
# export _JAVA_OPTIONS='-Dfile.encoding=UTF-8'  # Not use from Java 7


#
# Android SDK
#

# export ANDROID_JAVA_HOME=$JAVA_HOME
export ANDROID_JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
export ANDROID_HOME=$HOME/Library/android-sdk-macosx
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# Android Studio
export STUDIO_JDK=$(/usr/libexec/java_home -v 1.7 | sed -e "s/\/Contents\/Home//")


#
# Android NDK -> .bash_local
#

# export ANDROID_NDK_HOME=$HOME/Library/android-ndk-r10b
# export PATH=$ANDROID_NDK_HOME:$PATH


#
# Go
#

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
