#!/usr/bin/env bash
## -*- mode: sh-mode; coding: utf-8 -*-

# The Fuck
eval "$(thefuck --alias)"

#
# gitignore.io https://www.gitignore.io/
#

function gi() {
  curl -s https://www.gitignore.io/api/$@ ;
}
