##
## Install command-line tools using Homebrew
##

# Make sure we're using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install tools
install coreutils
install bash
install ack
install colordiff
install tree
install wget
install vim
install htop

install bash-completion
install thefuck
install gnu-sed
install git
install hub
install diff-so-fancy
install subversion
install sl
install lv
install the_silver_searcher
install the_platinum_searcher
install ripgrep
install peco
install jo
install fpp
install go
install shellcheck
install sqlite
link sqlite --force
install mongodb
install mycli
install heroku
install multimarkdown
install pandoc
install diff-pdf
install jq
install tig
install gibo
install w3m
install httpie
install mitmproxy
install nkf
install ffmpeg
install gifsicle
install mp3splt
install mp3wrap
install terminal-notifier
install pwgen
install dark-mode
install hicolor-icon-theme

# Add tap

install github/gh/gh


# Generate synbolic link for GUI applications
linkapps

# Remove outdated versions from the cellar
# and remove dead symlinks from the Homebrew prefix.
cleanup
prune
